image: alpine/edge
secrets:
  - a9fd4315-9f42-42d3-b747-3bdfca113eec
sources:
  - git+ssh://git@git.sr.ht/~rosin/lark
tasks:
  - mirror-to-github: |
      cd ~/lark
      ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
      git remote add github git@github.com:somniamble/lark.git
      git push --mirror github