# Test document contents:

This is a paragraph.
It's a single block element, because 
it is not divided by consequetive newlines.

This is a second paragraph.

This paragraph has: 
*bold text*, 
_italicized text_, 
`inline-code`, 
[[a wikilink]], 
and an [outlink](https://example.com)
    
# This is a heading
## This is a subheading

```
this is a fenced multiline code block

The contents thereof should be fixed-width text.
It's verbatim, so:
*this is not bold*
_this is not italicized_
`this is not inline-code`
> this is not a quote


this is not a separate paragraph
``` The text after the closed fence is ignored.